name: Static Site

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./src
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

        # setup node
      - id: 'setup-node'
        name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: './src/yarn.lock'
        
        # install yarn
      - id: 'install-yarn'
        name: Install Yarn
        run: npm install -g yarn

      # build static site
      - id: 'build'
        name: 'Install Modules And Build'
        run: |
          yarn install
          yarn build

      # configure gcloud `setup-gcloud` automatically
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/811440364468/locations/global/workloadIdentityPools/github/providers/my-repo'
          service_account: 'gh-actions-service-account@cs-1660-404523.iam.gserviceaccount.com'

      # upload files to GCS
      - id: 'upload-static-files'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'src/out'
          destination: 'static-site-project'
          parent: false

